### ISSUE TITLE
Create link to publication in Shiny app

### ISSUE THREAD

**Issue by rbutleriii** [Longo-Lab/de_dashboards#14]
We want to have a link to the paper when it comes out in the Shiny app. Thinking in the header (mostly blank) right adjusted. Can be a link with the tag "Please cite [our publication](url) if this is useful in your work"

**Comment by cyouh95** [comment]
Citation added to header (see [here](https://github.com/Longo-Lab/de_dashboards/issues/17#issuecomment-1754205093))

**Comment by rbutleriii** [comment]
Looks Great!
