### ISSUE TITLE
Add to tutorial instructions for style.css configuration

### ISSUE THREAD

**Issue by rbutleriii** [Longo-Lab/de_dashboards#16]
Add to the deploy instructions in the README.md to include a description of the sections to uncomment for each use case.

**Comment by rbutleriii** [comment]
We can look at the `t41b_BD10-2_stim` dashboard as reference, still a little off and needs adjusting.

**Comment by rbutleriii** [comment]
Went ahead and test deployed for `T41B_C31_aged` de dashboard. Should also add the `app.R` customizations to the readme as well (see in `00-commands.sh`):
```
# # publish app
# cp /labs/flongo/de_dashboards/app.R ./app.R
# cp -R /labs/flongo/de_dashboards/www .
# In www/style.css, uncomment the appropriate sections as indicated within the file:

    # For bulk data, uncomment rule to hide sidebar tabs
    # For DE dashboards, uncomment rule for formatting L2FC correlation tab

# In app.R, uncomment/label appropriate sections within the file:

    # For Project Selection section, add names of de projects
    # For dashboardHeader, uncomment authors and add title
    # For render sidebar text, uncomment "Wt drug effect" group if it exists
```

**Comment by cyouh95** [comment]
Updated instructions to [`README.md`](https://github.com/Longo-Lab/de_dashboards#deploying-to-shinyappsio)
