### ISSUE TITLE
Cache for shiny app fix

### ISSUE THREAD

**Issue by rbutleriii** [Longo-Lab/de_dashboards#3]
Three main conditions it could fail under
- [ ] lose tables (reactive graphs) on shinyapps.io after a few minutes
- [ ] when idle must reestablish cache
- [ ] Does local version caching work? 
- [ ] Does turning off shinyapps built in caching button resolve it

**Comment by cyouh95** [comment]
Using saved `.RData` files now instead of caching (see #4). Load time is <10s.

**Comment by rbutleriii** [comment]
I think this one can be marked as resolved and moved to the done column in the de_dashboard project
